// Structure des réalisations détaillées basée sur le fichier Excel fourni (Classeur1.xlsx)
// 5 rubriques : Production Sci., Projets, Rayonnement, Formation, Prestations

export const REALISATIONS_SECTIONS = [
  {
    id: 'real_production',
    title: 'Publications scientifiques',
    icon: '🔬',
    color: '#047481',
    description: 'Saisir chaque publication — Format Scopus',
    table: {
      cols: [
        { id: 'authors',      label: 'Author(s)',                 type: 'text',   width: 160, required: true  },
        { id: 'title',        label: 'Document title',            type: 'text',   width: 200, required: true  },
        { id: 'year',         label: 'Year',                      type: 'select', width: 80,  required: true,
          options: Array.from({length:10},(_,i)=>`${2025+i}`) },
        { id: 'semester',     label: 'Semestre',                  type: 'select', width: 90,  required: true,
          options: ['S1','S2'] },
        { id: 'eid',          label: 'EID (Scopus)',              type: 'text',   width: 140, required: false },
        { id: 'source',       label: 'Source title',              type: 'text',   width: 160, required: true  },
        { id: 'vol_pages',    label: 'Volume, issue, pages',      type: 'text',   width: 130, required: false },
        { id: 'citations',    label: 'Citations',                 type: 'number', width: 80,  required: false, min:0 },
        { id: 'doc_type',     label: 'Source & document type',    type: 'select', width: 140, required: true,
          options: ['Journal Article','Conference Paper','Review','Book Chapter','Book','Report','Other'] },
        { id: 'stage',        label: 'Publication stage',         type: 'select', width: 130, required: true,
          options: ['Final','Article in Press','Accepted','Submitted'] },
        { id: 'doi',          label: 'DOI',                       type: 'doi',    width: 180, required: false },
        { id: 'open_access',  label: 'Open access',               type: 'select', width: 120, required: false,
          options: ['None','Gold OA','Green OA','Hybrid Gold','Diamond OA'] },
        { id: 'affiliations', label: 'Affiliations',              type: 'text',   width: 140, required: false },
        { id: 'comment',      label: 'Commentaire GSMI',          type: 'text',   width: 140, required: false },
      ],
      aggregates: [
        { label: 'Total publications',       fn: rows => rows.length },
        { label: 'Publications Final',       fn: rows => rows.filter(r=>r.stage==='Final').length },
        { label: 'Accepté / In Press',       fn: rows => rows.filter(r=>['Accepted','Article in Press'].includes(r.stage)).length },
        { label: 'Citations totales',        fn: rows => rows.reduce((a,r)=>a+(+r.citations||0),0) },
        { label: 'Open Access',              fn: rows => rows.filter(r=>r.open_access && r.open_access!=='None').length },
        { label: 'Journal Articles',         fn: rows => rows.filter(r=>r.doc_type==='Journal Article').length },
        { label: 'Conference Papers',        fn: rows => rows.filter(r=>r.doc_type==='Conference Paper').length },
        { label: 'S1 publications',          fn: rows => rows.filter(r=>r.semester==='S1').length },
        { label: 'S2 publications',          fn: rows => rows.filter(r=>r.semester==='S2').length },
      ],
    },
  },
  {
    id: 'real_projets',
    title: 'Projets de recherche',
    icon: '💰',
    color: '#057A55',
    description: 'Liste des projets soumis, en cours et obtenus',
    table: {
      cols: [
        { id: 'annee',       label: 'Année',          type: 'select', width: 80,  required: true,
          options: Array.from({length:10},(_,i)=>`${2025+i}`) },
        { id: 'type',        label: 'Type',           type: 'select', width: 110, required: true,
          options: ['National','International','Industriel','Institutionnel UM6P','Bilatéral'] },
        { id: 'intitule',    label: 'Intitulé',       type: 'text',   width: 200, required: true  },
        { id: 'role',        label: 'Rôle',           type: 'select', width: 110, required: true,
          options: ['PI','Co-PI','Participant','Coordinateur','Consultant'] },
        { id: 'statut',      label: 'Statut',         type: 'select', width: 100, required: true,
          options: ['Soumis','Accepté','Rejeté','En cours','Terminé'] },
        { id: 'financeur',   label: 'Financeur',      type: 'text',   width: 130, required: false },
        { id: 'budget',      label: 'Budget (MAD)',   type: 'number', width: 120, required: false, min:0 },
        { id: 'part_um6p',   label: 'Part UM6P (%)', type: 'number', width: 100, required: false, min:0, max:100 },
        { id: 'debut',       label: 'Début',          type: 'text',   width: 90,  required: false },
        { id: 'fin',         label: 'Fin',            type: 'text',   width: 90,  required: false },
        { id: 'multi_inst',  label: 'Multi-inst.',    type: 'select', width: 90,  required: false,
          options: ['Oui','Non'] },
        { id: 'comment',     label: 'Commentaire',    type: 'text',   width: 140, required: false },
      ],
      aggregates: [
        { label: 'Projets soumis',       fn: rows => rows.filter(r=>['Soumis','Accepté','Rejeté'].includes(r.statut)).length },
        { label: 'Projets obtenus',      fn: rows => rows.filter(r=>['Accepté','En cours','Terminé'].includes(r.statut)).length },
        { label: 'Taux de succès',       fn: rows => {
            const s=rows.filter(r=>['Soumis','Accepté','Rejeté'].includes(r.statut)).length
            const o=rows.filter(r=>['Accepté','En cours','Terminé'].includes(r.statut)).length
            return s>0 ? `${Math.round(o/s*100)}%` : 'N/A'
          }},
        { label: 'Budget total (MAD)',   fn: rows => rows.filter(r=>['Accepté','En cours','Terminé'].includes(r.statut)).reduce((a,r)=>a+(+r.budget||0),0).toLocaleString('fr-MA') },
        { label: 'Projets internationaux', fn: rows => rows.filter(r=>['International','Bilatéral'].includes(r.type)).length },
      ],
    },
  },
  {
    id: 'real_rayonnement',
    title: 'Rayonnement & Valorisation',
    icon: '🌍',
    color: '#5521B5',
    description: 'Conférences, brevets, prototypes, transferts',
    table: {
      cols: [
        { id: 'annee',     label: 'Année',         type: 'select', width: 80,  required: true,
          options: Array.from({length:10},(_,i)=>`${2025+i}`) },
        { id: 'categorie', label: 'Catégorie',     type: 'select', width: 160, required: true,
          options: ['Conférence internationale','Communication invitée','Brevet déposé','Brevet accepté','Prototype','Transfert technologique','Startup','Prix & Distinction'] },
        { id: 'sous_type', label: 'Sous-type',     type: 'text',   width: 120, required: false },
        { id: 'titre',     label: 'Titre',         type: 'text',   width: 200, required: true  },
        { id: 'support',   label: 'Événement',     type: 'text',   width: 150, required: false },
        { id: 'pays',      label: 'Pays',          type: 'text',   width: 90,  required: false },
        { id: 'portee',    label: 'Portée',        type: 'select', width: 100, required: false,
          options: ['Nationale','Internationale','Régionale'] },
        { id: 'statut',    label: 'Statut',        type: 'select', width: 100, required: false,
          options: ['Prévu','Réalisé','Soumis','Accepté'] },
        { id: 'trl',       label: 'TRL',           type: 'select', width: 70,  required: false,
          options: ['N/A','TRL 1','TRL 2','TRL 3','TRL 4','TRL 5','TRL 6','TRL 7','TRL 8','TRL 9'] },
        { id: 'revenus',   label: 'Revenus (MAD)', type: 'number', width: 110, required: false, min:0 },
        { id: 'date',      label: 'Date',          type: 'text',   width: 90,  required: false },
        { id: 'comment',   label: 'Commentaire',   type: 'text',   width: 140, required: false },
      ],
      aggregates: [
        { label: 'Conférences int.',      fn: rows => rows.filter(r=>r.categorie==='Conférence internationale').length },
        { label: 'Communications invitées',fn: rows => rows.filter(r=>r.categorie==='Communication invitée').length },
        { label: 'Brevets déposés',       fn: rows => rows.filter(r=>r.categorie==='Brevet déposé').length },
        { label: 'Brevets acceptés',      fn: rows => rows.filter(r=>r.categorie==='Brevet accepté').length },
        { label: 'Prototypes/Transferts', fn: rows => rows.filter(r=>['Prototype','Transfert technologique','Startup'].includes(r.categorie)).length },
      ],
    },
  },
  {
    id: 'real_formation',
    title: 'Formation & Encadrement',
    icon: '🎓',
    color: '#5521B5',
    description: 'Heures par semestre, type et activité',
    table: {
      cols: [
        { id: 'semester',  label: 'Semestre',      type: 'select', width: 80,  required: true,
          options: ['S1','S2'] },
        { id: 'type_form', label: 'Type',          type: 'select', width: 160, required: true,
          options: ['Formation Initiale','Formation Exécutive','Formation Doctorale'] },
        { id: 'activite',  label: 'Activité',      type: 'select', width: 180, required: true,
          options: ['Animation cours','Conception cours','Préparation examens','Encadrement PFE','Encadrement stages','Conception programmes','Cours doctoraux','Encadrement thèses'] },
        { id: 'filiere',   label: 'Filière / Programme', type: 'text', width: 160, required: false },
        { id: 'h_prev',    label: 'H. Prévues',    type: 'number', width: 90,  required: false, min:0 },
        { id: 'h_real',    label: 'H. Réalisées',  type: 'number', width: 90,  required: true,  min:0 },
        { id: 'comment',   label: 'Commentaire',   type: 'text',   width: 140, required: false },
      ],
      aggregates: [
        { label: 'H. Formation Initiale',  fn: rows => rows.filter(r=>r.type_form==='Formation Initiale').reduce((a,r)=>a+(+r.h_real||0),0) },
        { label: 'H. Formation Exécutive', fn: rows => rows.filter(r=>r.type_form==='Formation Exécutive').reduce((a,r)=>a+(+r.h_real||0),0) },
        { label: 'H. Formation Doctorale', fn: rows => rows.filter(r=>r.type_form==='Formation Doctorale').reduce((a,r)=>a+(+r.h_real||0),0) },
        { label: 'Total heures S1',        fn: rows => rows.filter(r=>r.semester==='S1').reduce((a,r)=>a+(+r.h_real||0),0) },
        { label: 'Total heures S2',        fn: rows => rows.filter(r=>r.semester==='S2').reduce((a,r)=>a+(+r.h_real||0),0) },
      ],
    },
  },
  {
    id: 'real_prestations',
    title: 'Prestations de service',
    icon: '💼',
    color: '#B45309',
    description: 'Missions d\'expertise, consulting, formations exécutives',
    table: {
      cols: [
        { id: 'annee',    label: 'Année',          type: 'select', width: 80,  required: true,
          options: Array.from({length:10},(_,i)=>`${2025+i}`) },
        { id: 'intitule', label: 'Intitulé mission',type: 'text',  width: 200, required: true  },
        { id: 'type',     label: 'Type',           type: 'select', width: 140, required: true,
          options: ['Expertise technique','Audit / Diagnostic','Formation continue','Consulting','Étude de faisabilité','Autre'] },
        { id: 'client',   label: 'Client',         type: 'text',   width: 140, required: false },
        { id: 'role',     label: 'Rôle',           type: 'select', width: 130, required: false,
          options: ['Responsable (lead)','Co-responsable','Contributeur','Expert associé'] },
        { id: 'jours',    label: 'Jours homme',    type: 'number', width: 90,  required: false, min:0 },
        { id: 'tarif',    label: 'Tarif/j (MAD)', type: 'number', width: 100, required: false, min:0 },
        { id: 'montant',  label: 'Montant (MAD)', type: 'number', width: 110, required: false, min:0 },
        { id: 'statut',   label: 'Statut',         type: 'select', width: 100, required: false,
          options: ['Planifié','En cours','Réalisé','Facturé','Annulé'] },
        { id: 'debut',    label: 'Début',          type: 'text',   width: 90,  required: false },
        { id: 'fin',      label: 'Fin',            type: 'text',   width: 90,  required: false },
        { id: 'impact',   label: 'Impact',         type: 'select', width: 90,  required: false,
          options: ['Faible','Moyen','Élevé','Très élevé'] },
        { id: 'comment',  label: 'Commentaire',   type: 'text',   width: 140, required: false },
      ],
      aggregates: [
        { label: 'Nb. prestations',      fn: rows => rows.length },
        { label: 'Revenus totaux (MAD)', fn: rows => rows.reduce((a,r)=>a+(+r.montant||0),0).toLocaleString('fr-MA') },
        { label: 'Missions pilotées',    fn: rows => rows.filter(r=>r.role==='Responsable (lead)').length },
        { label: 'Jours totaux',         fn: rows => rows.reduce((a,r)=>a+(+r.jours||0),0) },
      ],
    },
  },
]
